### ISSUE TITLE
1

### ISSUE THREAD

**Issue by RicardoCZ** [zyujs/clanbattle_info#1]
出现 clanbattle_info插件检测到新的提交记录,请及时更新.  时要怎么处理

**Comment by zyujs** [comment]
cd clanbattle_info
git pull
重启bot

**Comment by RicardoCZ** [comment]
最新的自动报刀工具在提示 已继续 之后，后续无任何消息发送且后台无报错



---Original---

**Comment by zyujs** [comment]
登录毕方看看你有没有数据

**Comment by RicardoCZ** [comment]
确实没有！请问有解决办法吗



---Original---

**Comment by zyujs** [comment]
这你得去毕方提issue

**Comment by RicardoCZ** [comment]
bigfun那边有数据了，现在后台出来了这个报错



---Original---
