### ISSUE TITLE
特殊字符昵称无法匹配

### ISSUE THREAD

**Issue by ArcherWS** [zyujs/clanbattle_info#10]
昵称":p在群 cc"匹配失败，显示找不到该成员。
目测是yobot.py 228行#生成昵称-QQ对应表部分的问题。
在下不懂python，麻烦管理解决一下？

**Comment by zyujs** [comment]
使用命令手动绑定

**Comment by ArcherWS** [comment]
问题已解决。
是游戏昵称的问题，该成员在游戏昵前加了半角空格，qq昵称不支持昵称前加空格，导致一直匹配不上……
