### ISSUE TITLE
能否增加一个参数 关闭 往群里发送的消息

### ISSUE THREAD

**Issue by MrRumpel** [zyujs/clanbattle_info#4]
embedded_yobot_add_challenge

这个方法里的

msg = 'yobot新增出刀记录:\n' + str(result)

会造成同步数据的时候在群内光速刷屏

**Comment by zyujs** [comment]
你可以自己注释掉send_group_msg, 同步完成再恢复.

**Comment by MrRumpel** [comment]
已经通过注释掉send_group_msg方法完成数据同步了，插件非常棒，加油

**Comment by MrRumpel** [comment]
已经通过注释掉send_group_msg方法完成数据同步了，插件非常棒，加油
